 * Serving Flask app 'server'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
[33mPress CTRL+C to quit[0m
[2024-05-31 15:35:06,069] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/opendevin/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/opendevin/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/opendevin/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/opendevin/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/workspace/server.py", line 50, in handle_request
    app_name, access_key = data.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
127.0.0.1 - - [31/May/2024 15:35:06] "[35m[1mPOST / HTTP/1.1[0m" 500 -
